name: TreasureChest
version: 1.7.10-1.2.0
author: Himmelt
main: org.soraworld.treasure.TreasureChest
website: https://github.com/Himmelt/TreasureChest
description: TreasureChest.

commands:
  treasure:
    description: "TreasureChest - https://github.com/Himmelt/TreasureChest"
    usage: "/treasure create|copy|paste|open|run|stop"
    permission: treasure.admin
    permission-message: "You have no permission <treasure.admin>"
permissions:
  treasure.admin:
    default: op
  treasure.use:
    default: op
