name: TreasureChest
version: 1.7.10-1.0.7
author: Himmelt
main: org.soraworld.treasure.TreasureChest
website: https://github.com/Himmelt/TreasureChest
description: TreasureChest.

commands:
  treasure:
    description: "Treasure - https://github.com/Himmelt/TreasureChest"
    usage: "[Treasure] /treasure save|reload|lang|create|copy|paste|open|run|stop"
    permission: treasure.admin
    permission-message: "[Treasure] You have no permission <treasure.admin>"
permissions:
  treasure.admin:
    default: op
  treasure.use:
    default: op
